name: Develop CI/CD to S3

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19' 

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build 

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1 # Replace with your AWS region

      - name: Upload to S3
        run: aws s3 cp dist/ckeditor-poc-frontend/browser s3://dev.pentagonforce.com/ --recursive --exclude "*" --include "*"